-- Collapse aphydle.attempts to one row per player-day-puzzle.
--
-- The original schema captured one row per individual guess, keyed by
-- (anon_id, puzzle_no, attempt_no). That produces up to 10 rows per
-- session and makes day-over-day analysis noisy. Anon ids already
-- rotate every UTC day, so (anon_id, puzzle_no) is enough to pin a
-- row to a single player-day-puzzle. The client now upserts on that
-- key with the latest attempt count + outcome, so every refresh just
-- overwrites the same row.

-- Drop the per-attempt uniqueness so the same (anon_id, puzzle_no)
-- can be touched repeatedly without a 23505. The constraint name was
-- auto-generated by `unique (...)` in 0002.
alter table aphydle.attempts
    drop constraint if exists attempts_anon_id_puzzle_no_attempt_no_key;

-- New uniqueness: one row per player-day-puzzle.
alter table aphydle.attempts
    add constraint attempts_anon_id_puzzle_no_key
    unique (anon_id, puzzle_no);

-- Anon needs UPDATE in addition to INSERT for upsert to work, plus an
-- RLS policy that lets a row be rewritten as long as the new payload
-- still passes the same shape checks the insert policy enforces.
grant update on aphydle.attempts to anon, authenticated;

drop policy if exists "update attempt" on aphydle.attempts;
create policy "update attempt"
    on aphydle.attempts
    for update
    to anon, authenticated
    using (true)
    with check (
        anon_id is not null
        and length(anon_id) between 8 and 128
        and attempt_no between 1 and 10
    );
